[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/samplersLib"]

# This ensures Hatch doesn't exclude the binaries
[tool.hatch.build]
artifacts = [
    "*.pyd",
    "*.so",
]
exclude = [
  # Exclude any unwanted files that might be picked up by default
  "src/samplersLib/__pycache__",
  "src/samplersLib/*.pyc",
  "src/samplersLib/*.pyo"
]

[project]
name = "OMADS"
version = "2601.0"
requires-python = ">=3.10"
description = "Optimization using Mesh Adaptive Direct Search (MADS)"
readme = "README.md"

authors = [
    { name = "Ahmed H. Bayoumy", email = "ahmed.bayoumy@mail.mcgill.ca" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]

dependencies = [
    "deap==1.4",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "paramiko>=3.4.0",
    "requests>=2.32.5",
    "samplerslib>=2602.0",
    "scipy>=1.15.3",
]

[project.optional-dependencies]
visualization = [
    "matplotlib>=3.10.8",
    "plotly>=6.5.0",
]

test = [
    "pytest>=8.0",
    "pytest-cov>=7.0.0",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

[tool.ruff]
line-length = 127

[tool.ruff.lint]
# E9, F63, F7, F82 are standard in Ruff's default 'E' and 'F' selections
select = ["E", "F", "C90"] 

[tool.ruff.lint.mccabe]
max-complexity = 10

